scripts:
  - name: Установка зависимостей
    script: |
      echo "Текущая директория: $(pwd)"
      ls -la  # Проверка содержимого
      
      # Явно указываем путь к Podfile
      export LANG=en_US.UTF-8
      pod install --project-directory=.
      
      # Дополнительная проверка
      echo "Проверка структуры после pod install:"
      ls -la VKMusicApp.xcworkspace
